---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - nsxt_answerfile_base.yml
    - nsxt_answerfile_switching_routing.yml
  tasks:
    - name: Create a new IP address block
      nsxt_ip_sets:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        display_name: "{{item.display_name}}"
        ip_addresses: "{{item.ip_addresses}}"
        state: absent
        validate_certs: False
      with_items:
        - "{{nsxt_ip_sets}}"