---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - nsxt_answerfile_base.yml
    - nsxt_answerfile_firewall.yml
  tasks:
    - name: Create a new IP Set
      nsxt_ip_sets:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        display_name: "{{ item.display_name }}"
        ip_addresses: "{{ item.ip_addresses }}"
        state: "{{ item.state }}"
        validate_certs: False
      with_items:
        - "{{ nsxt_ip_sets }}"
    - name: Create a new NS Group
      nsxt_ns_groups:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        display_name: "{{ item.display_name }}"
        members: "{{ item.members | default([]) }}"
        membership_criteria: "{{ item.membership_criteria | default([]) }}"
        resource_type: "NSGroup"
        state: "{{ item.state }}"
        validate_certs: False
      with_items:
        - "{{ nsxt_ns_groups }}"
    - name: Create DFW Section with Rules
      nsxt_firewall_section_with_rules:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        applied_tos: "{{ item.applied_tos | default([]) }}"
        display_name: "{{ item.display_name }}"
        description: "{{ item.description | default(omit) }}"
        modify_placement: "{{ item.modify_placement | default(omit) }}"
        rules: "{{ item.rules | default([]) }}"
        section_placement: "{{ item.section_placement | default(omit) }}"
        section_type: LAYER3
        state: "{{ item.state }}"
        stateful: "{{ item.stateful | default(True) }}"
        tags: "{{ item.tags | default([]) }}"
        validate_certs: False
      with_items:
        - "{{ nsxt_dfw_section_with_rules }}"