## The tasks in this section are currently no idempotent

---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - nsxt_answerfile_base.yml
    - nsxt_answerfile_switching_routing.yml
  tasks:
    # Next 2 sections create the T0 uplink
    - name: Create a Logical Port for T0 uplinks
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.logical_switch_port_name}}"
        logical_switch_name: "{{item.logical_switch_name}}"
        admin_state: "UP"
        state: "present"
      ignore_errors: yes
      register: result_t0
      with_items:
        - "{{logical_router_ports_t0_up}}"

    - name: Create logical router port for T0 uplinks
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.0.display_name}}"
        resource_type: "LogicalRouterUpLinkPort"
        logical_router_name: "{{item.0.logical_router_name}}"
        linked_logical_switch_port_id:
          target_type: "LogicalPort"
          target_display_name: "{{item.0.logical_switch_port_name}}"
          target_id: "{{item.1['id']}}" # TODO Only supports single uplink
        edge_cluster_member_index:
          0
        subnets:
        - ip_addresses:
          - "{{item.0.ip_addresses}}"
          prefix_length: "{{item.0.prefix_length}}"
        state: "present"
      ignore_errors: yes
      with_together:
        - "{{logical_router_ports_t0_up}}"
        - "{{result_t0.results}}"
        
    # Next 2 sections create a T1 down link
    - name: Create a Logical Port for LS uplinks
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.logical_switch_port_name}}"
        logical_switch_name: "{{item.logical_switch_name}}"
        admin_state: "UP"
        state: "present"
      ignore_errors: yes
      register: result_ls
      with_items:
        - "{{logical_router_ports_ls_up}}"
    - name: Create logical router port for LS uplinks
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.0.display_name}}"
        resource_type: "LogicalRouterDownLinkPort"
        logical_router_name: "{{item.0.logical_router_name}}"
        linked_logical_switch_port_id:
          target_type: "LogicalPort"
          target_display_name: "{{item.0.logical_switch_port_name}}"
          target_id: "{{item.1['id']}}"
        subnets:
        - ip_addresses:
          - "{{item.0.ip_addresses}}"
          prefix_length: "{{item.0.prefix_length}}"
        state: "present"
      ignore_errors: yes
      with_together:
        - "{{logical_router_ports_ls_up}}"
        - "{{result_ls.results}}"